"""Pipelines definitions for image transformations and augmentations."""
from src.data import Transformation

PipeType = list[list[Transformation]]

simple_pipeline: PipeType = [
    [Transformation.MIRROR, Transformation.ROTATE],
    [Transformation.MIRROR, Transformation.NOISE],
    [Transformation.MIRROR],
]

single_pipelines: PipeType = [
    # SINGLES
    [Transformation.ROTATE],
    [Transformation.MIRROR],
    [Transformation.SUB],
    [Transformation.SHUFFLE],
    [Transformation.CIRCLES],
    [Transformation.INVERT],
    [Transformation.SHIFT_COLOR],
    [Transformation.NOISE],
]

full_pipelines: PipeType = [
    # SINGLES
    [Transformation.ROTATE],
    [Transformation.MIRROR],
    [Transformation.SUB],
    [Transformation.SHUFFLE],
    [Transformation.CIRCLES],
    [Transformation.INVERT],
    [Transformation.SHIFT_COLOR],
    [Transformation.NOISE],
    # PAIRS
    [Transformation.ROTATE, Transformation.MIRROR],
    [Transformation.SUB, Transformation.ROTATE],
    [Transformation.SHUFFLE, Transformation.ROTATE],
    [Transformation.CIRCLES, Transformation.ROTATE],
    [Transformation.ROTATE, Transformation.INVERT],
    [Transformation.ROTATE, Transformation.SHIFT_COLOR],
    [Transformation.ROTATE, Transformation.NOISE],
    [Transformation.MIRROR, Transformation.SUB],
    [Transformation.MIRROR, Transformation.SHUFFLE],
    [Transformation.MIRROR, Transformation.CIRCLES],
    [Transformation.MIRROR, Transformation.INVERT],
    [Transformation.MIRROR, Transformation.SHIFT_COLOR],
    [Transformation.MIRROR, Transformation.NOISE],
    [Transformation.SUB, Transformation.SHUFFLE],
    [Transformation.SUB, Transformation.CIRCLES],
    [Transformation.SUB, Transformation.INVERT],
    [Transformation.SUB, Transformation.SHIFT_COLOR],
    [Transformation.SUB, Transformation.NOISE],
    [Transformation.SHUFFLE, Transformation.CIRCLES],
    [Transformation.SHUFFLE, Transformation.INVERT],
    [Transformation.SHUFFLE, Transformation.SHIFT_COLOR],
    [Transformation.SHUFFLE, Transformation.NOISE],
    [Transformation.CIRCLES, Transformation.INVERT],
    [Transformation.CIRCLES, Transformation.SHIFT_COLOR],
    [Transformation.CIRCLES, Transformation.NOISE],
    [Transformation.INVERT, Transformation.SHIFT_COLOR],
    [Transformation.INVERT, Transformation.NOISE],
    [Transformation.SHIFT_COLOR, Transformation.NOISE],
    # TRIOS
    [Transformation.SUB, Transformation.ROTATE, Transformation.MIRROR],
    [Transformation.SHUFFLE, Transformation.ROTATE, Transformation.MIRROR],
    [Transformation.CIRCLES, Transformation.ROTATE, Transformation.MIRROR],
    [Transformation.ROTATE, Transformation.MIRROR, Transformation.INVERT],
    [Transformation.ROTATE, Transformation.MIRROR, Transformation.SHIFT_COLOR],
    [Transformation.ROTATE, Transformation.MIRROR, Transformation.NOISE],
    [Transformation.SUB, Transformation.SHUFFLE, Transformation.ROTATE],
    [Transformation.SUB, Transformation.CIRCLES, Transformation.ROTATE],
    [Transformation.SUB, Transformation.INVERT, Transformation.ROTATE],
    [Transformation.SUB, Transformation.SHIFT_COLOR, Transformation.ROTATE],
    [Transformation.SUB, Transformation.NOISE, Transformation.ROTATE],
    [Transformation.SHUFFLE, Transformation.CIRCLES, Transformation.ROTATE],
    [Transformation.SHUFFLE, Transformation.INVERT, Transformation.ROTATE],
    [Transformation.SHUFFLE, Transformation.ROTATE, Transformation.SHIFT_COLOR],
    [Transformation.SHUFFLE, Transformation.ROTATE, Transformation.NOISE],
    [Transformation.ROTATE, Transformation.CIRCLES, Transformation.INVERT],
    [Transformation.ROTATE, Transformation.CIRCLES, Transformation.SHIFT_COLOR],
    [Transformation.ROTATE, Transformation.CIRCLES, Transformation.NOISE],
    [Transformation.INVERT, Transformation.ROTATE, Transformation.SHIFT_COLOR],
    [Transformation.INVERT, Transformation.ROTATE, Transformation.NOISE],
    [Transformation.ROTATE, Transformation.SHIFT_COLOR, Transformation.NOISE],
    [Transformation.MIRROR, Transformation.SUB, Transformation.SHUFFLE],
    [Transformation.MIRROR, Transformation.SUB, Transformation.CIRCLES],
    [Transformation.MIRROR, Transformation.SUB, Transformation.INVERT],
    [Transformation.MIRROR, Transformation.SUB, Transformation.SHIFT_COLOR],
    [Transformation.MIRROR, Transformation.SUB, Transformation.NOISE],
    [Transformation.MIRROR, Transformation.SHUFFLE, Transformation.CIRCLES],
    [Transformation.MIRROR, Transformation.SHUFFLE, Transformation.INVERT],
    [Transformation.MIRROR, Transformation.SHUFFLE, Transformation.SHIFT_COLOR],
    [Transformation.MIRROR, Transformation.SHUFFLE, Transformation.NOISE],
    [Transformation.MIRROR, Transformation.CIRCLES, Transformation.INVERT],
    [Transformation.MIRROR, Transformation.CIRCLES, Transformation.SHIFT_COLOR],
    [Transformation.MIRROR, Transformation.CIRCLES, Transformation.NOISE],
    [Transformation.MIRROR, Transformation.INVERT, Transformation.SHIFT_COLOR],
    [Transformation.MIRROR, Transformation.INVERT, Transformation.NOISE],
    [Transformation.MIRROR, Transformation.SHIFT_COLOR, Transformation.NOISE],
    [Transformation.SUB, Transformation.SHUFFLE, Transformation.CIRCLES],
    [Transformation.SUB, Transformation.SHUFFLE, Transformation.INVERT],
    [Transformation.SUB, Transformation.SHUFFLE, Transformation.SHIFT_COLOR],
    [Transformation.SUB, Transformation.SHUFFLE, Transformation.NOISE],
    [Transformation.SUB, Transformation.CIRCLES, Transformation.INVERT],
    [Transformation.SUB, Transformation.CIRCLES, Transformation.SHIFT_COLOR],
    [Transformation.SUB, Transformation.CIRCLES, Transformation.NOISE],
    [Transformation.SUB, Transformation.INVERT, Transformation.SHIFT_COLOR],
    [Transformation.SUB, Transformation.INVERT, Transformation.NOISE],
    [Transformation.SUB, Transformation.SHIFT_COLOR, Transformation.NOISE],
    [Transformation.SHUFFLE, Transformation.CIRCLES, Transformation.INVERT],
    [Transformation.SHUFFLE, Transformation.CIRCLES, Transformation.SHIFT_COLOR],
    [Transformation.SHUFFLE, Transformation.CIRCLES, Transformation.NOISE],
    [Transformation.SHUFFLE, Transformation.INVERT, Transformation.SHIFT_COLOR],
    [Transformation.SHUFFLE, Transformation.INVERT, Transformation.NOISE],
    [Transformation.SHUFFLE, Transformation.SHIFT_COLOR, Transformation.NOISE],
    [Transformation.CIRCLES, Transformation.INVERT, Transformation.SHIFT_COLOR],
    [Transformation.CIRCLES, Transformation.INVERT, Transformation.NOISE],
    [Transformation.CIRCLES, Transformation.SHIFT_COLOR, Transformation.NOISE],
    [Transformation.INVERT, Transformation.SHIFT_COLOR, Transformation.NOISE],
]
